//! pip-compile package-file adapter.
//!
//! Renovate reference:
//! - `lib/modules/manager/pip-compile/index.ts` `extractPackageFile`
//! - `lib/modules/manager/pip-compile/extract.spec.ts`
//!
//! The upstream manager delegates individual input files to the existing
//! pip_requirements, pip_setup, and pep621 extractors. Its full
//! `extractAllPackageFiles()` lock-file resolver is intentionally separate and
//! not implemented here.

use std::sync::LazyLock;

use regex::Regex;

use crate::extractors::{pep621, pip, pip_setup};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PipCompileDep {
    Pip(pip::PipExtractedDep),
    Pep621(pep621::Pep621ExtractedDep),
}

impl PipCompileDep {
    pub fn dep_name(&self) -> &str {
        match self {
            Self::Pip(dep) => &dep.name,
            Self::Pep621(dep) => &dep.name,
        }
    }

    pub fn dep_type(&self) -> Option<&str> {
        match self {
            Self::Pip(_) => None,
            Self::Pep621(dep) => Some(dep.dep_type.as_renovate_str()),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PipCompileExtract {
    pub deps: Vec<PipCompileDep>,
}

pub fn extract_package_file(content: &str, package_file: &str) -> Option<PipCompileExtract> {
    let deps = if package_file.ends_with(".in") {
        pip::extract_package_file(content)
            .deps
            .into_iter()
            .map(PipCompileDep::Pip)
            .collect()
    } else if package_file.ends_with("setup.py") {
        pip_setup::extract(content)
            .into_iter()
            .map(PipCompileDep::Pip)
            .collect()
    } else if package_file.ends_with("pyproject.toml") {
        pep621::extract_package_file(content)
            .ok()?
            .deps
            .into_iter()
            .map(PipCompileDep::Pep621)
            .collect()
    } else {
        return None;
    };

    Some(PipCompileExtract { deps })
}

/// Identifies which Renovate manager handles a given pip-compile source file.
///
/// Mirrors TypeScript `matchManager` in `lib/modules/manager/pip-compile/common.ts`.
pub fn match_manager(filename: &str) -> &'static str {
    if filename.ends_with("setup.py") {
        "pip_setup"
    } else if filename.ends_with("setup.cfg") {
        "setup-cfg"
    } else if filename.ends_with("pyproject.toml") {
        "pep621"
    } else if filename.ends_with(".in") || filename.ends_with(".txt") {
        "pip_requirements"
    } else {
        "unknown"
    }
}

static PYTHON_VERSION_RE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?s)^(?:#.*?\r?\n)*# This file is autogenerated by pip-compile with Python (?P<pythonVersion>\d+(?:\.\d+)*)\s",
    )
    .unwrap()
});

/// Extract the Python version from a pip-compile-generated file header.
///
/// Returns `None` when the version line cannot be found.
/// Mirrors TypeScript `extractPythonVersion` in `lib/modules/manager/pip-compile/common.ts`.
pub fn extract_python_version(content: &str) -> Option<String> {
    PYTHON_VERSION_RE
        .captures(content)
        .map(|cap| cap["pythonVersion"].to_owned())
}

/// Infer the directory from which pip-compile should be executed.
///
/// Mirrors `lib/modules/manager/pip-compile/utils.ts` `inferCommandExecDir()`.
/// Returns an error string when the output file argument has a basename
/// that does not match the output file path's basename.
pub fn infer_command_exec_dir(
    output_file_path: &str,
    output_file_arg: Option<&str>,
) -> Result<String, String> {
    let file_basename = std::path::Path::new(output_file_path)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("");
    let file_dir = std::path::Path::new(output_file_path)
        .parent()
        .and_then(|p| p.to_str())
        .map(|s| if s.is_empty() { "." } else { s })
        .unwrap_or(".");

    let Some(arg) = output_file_arg else {
        return Ok(file_dir.to_owned());
    };

    let arg_basename = std::path::Path::new(arg)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("");
    let arg_dir = std::path::Path::new(arg)
        .parent()
        .and_then(|p| p.to_str())
        .map(|s| if s.is_empty() { "." } else { s })
        .unwrap_or(".");

    if arg_basename != file_basename {
        return Err(format!(
            "Output file name mismatch: {arg_basename} vs {file_basename}"
        ));
    }

    // If the output arg has no directory component, command runs from file_dir
    if arg_dir == "." && file_dir != "." {
        return Ok(file_dir.to_owned());
    }

    // Strip common suffix components
    let mut exec_dir = file_dir.to_owned();
    for component in arg_dir.split('/').rev() {
        if component != "." && exec_dir.ends_with(component) {
            exec_dir.truncate(exec_dir.len() - component.len());
            // Clean up trailing slashes
            exec_dir = exec_dir.trim_end_matches('/').to_owned();
            if exec_dir.is_empty() {
                exec_dir = ".".to_owned();
            }
        } else {
            break;
        }
    }

    Ok(exec_dir)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Ported: "returns object for requirements.in" — lib/modules/manager/pip-compile/extract.spec.ts line 40
    #[test]
    fn returns_object_for_requirements_in() {
        let package_file = extract_package_file(
            "attrs==23.1.0 \\\n    --hash=sha256:abc123\n",
            "requirements.in",
        )
        .expect("package file");

        assert_eq!(package_file.deps[0].dep_name(), "attrs");
    }

    // Ported: "returns object for setup.py" — lib/modules/manager/pip-compile/extract.spec.ts line 50
    #[test]
    fn returns_object_for_setup_py() {
        let package_file = extract_package_file(
            r#"
from setuptools import setup

setup(
    install_requires=[
        "celery>=5.0",
    ],
)
"#,
            "lib/setup.py",
        )
        .expect("package file");

        assert_eq!(package_file.deps[0].dep_name(), "celery");
    }

    // Ported: "returns object for pyproject.toml" — lib/modules/manager/pip-compile/extract.spec.ts line 60
    #[test]
    fn returns_object_for_pyproject_toml() {
        let package_file = extract_package_file(
            r#"
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "test-project"
requires-python = ">=3.11"
version = "1.2.3"
dependencies = [
  "aiohttp",
  "pydantic>=2.0.0",
]

[project.optional-dependencies]
dev = [
  "black",
  "flake8",
]
"#,
            "pyproject.toml",
        )
        .expect("package file");

        assert_eq!(package_file.deps[0].dep_type(), Some("requires-python"));
        assert_eq!(package_file.deps[1].dep_name(), "aiohttp");
    }

    // Ported: "returns null on not supported package files" — lib/modules/manager/pip-compile/extract.spec.ts line 93
    #[test]
    fn returns_null_on_not_supported_package_files() {
        for package_file in ["random.py", "app.cfg", "already_locked.txt", "setup.cfg"] {
            assert!(extract_package_file("some content", package_file).is_none());
        }
    }

    // Ported: "returns object on correct options" (case 1) — lib/modules/manager/pip-compile/utils.spec.ts line 5
    #[test]
    fn infer_exec_dir_same_subdir() {
        let result = infer_command_exec_dir("subdir/reqs.txt", Some("subdir/reqs.txt")).unwrap();
        assert_eq!(result, ".");
    }

    // Ported: "returns object on correct options" (case 2) — lib/modules/manager/pip-compile/utils.spec.ts line 5
    #[test]
    fn infer_exec_dir_output_in_parent() {
        let result = infer_command_exec_dir("subdir/reqs.txt", Some("reqs.txt")).unwrap();
        assert_eq!(result, "subdir");
    }

    // Ported: "throw if --output-file basename differs from path" — lib/modules/manager/pip-compile/utils.spec.ts line 23
    #[test]
    fn infer_exec_dir_throws_on_basename_mismatch() {
        let result = infer_command_exec_dir("subdir/requirements.txt", Some("hey.txt"));
        assert!(result.is_err());
        assert!(result.unwrap_err().contains("mismatch"));
    }

    // --- matchManager tests ---

    // Ported: "matches pip_setup setup.py" — lib/modules/manager/pip-compile/common.spec.ts line 373
    #[test]
    fn match_manager_setup_py() {
        assert_eq!(match_manager("setup.py"), "pip_setup");
    }

    // Ported: "matches setup-cfg setup.cfg" — lib/modules/manager/pip-compile/common.spec.ts line 377
    #[test]
    fn match_manager_setup_cfg() {
        assert_eq!(match_manager("setup.cfg"), "setup-cfg");
    }

    // Ported: "matches pep621 pyproject.toml" — lib/modules/manager/pip-compile/common.spec.ts line 381
    #[test]
    fn match_manager_pyproject_toml() {
        assert_eq!(match_manager("pyproject.toml"), "pep621");
    }

    // Ported: "matches pip_requirements any .in file" — lib/modules/manager/pip-compile/common.spec.ts line 385
    #[test]
    fn match_manager_in_file() {
        assert_eq!(match_manager("file.in"), "pip_requirements");
        assert_eq!(match_manager("another_file.in"), "pip_requirements");
    }

    // Ported: "matches pip_requirements any .txt file" — lib/modules/manager/pip-compile/common.spec.ts line 390
    #[test]
    fn match_manager_txt_file() {
        assert_eq!(match_manager("file.txt"), "pip_requirements");
        assert_eq!(match_manager("another_file.txt"), "pip_requirements");
    }

    // --- extractPythonVersion tests ---

    fn pip_compile_header(python_version: &str) -> String {
        format!(
            "#\n# This file is autogenerated by pip-compile with Python {python_version}\n# by the following command:\n#\n#    pip-compile reqs.in\n#\n"
        )
    }

    // Ported: "extracts Python version from valid header" — lib/modules/manager/pip-compile/common.spec.ts line 220
    #[test]
    fn extract_python_version_valid_header() {
        let header = pip_compile_header("3.11");
        assert_eq!(extract_python_version(&header).as_deref(), Some("3.11"));
    }

    // Ported: "returns undefined if version cannot be extracted" — lib/modules/manager/pip-compile/common.spec.ts line 229
    #[test]
    fn extract_python_version_empty_content() {
        assert!(extract_python_version("").is_none());
    }
}
