#!/usr/bin/env python3
"""One-time bootstrap: create docs/parity/modules.md.

Combines:
- the live coverage analysis from parity_coverage.py
- the rolled-up Impl status from derive_module_impl.py
into the new module ledger. After this runs, the ledger is regenerated by
`parity_coverage.py ledger`, which carries Impl/Notes forward from the
existing file.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "scripts"
OUT = ROOT / "docs/parity/modules.md"

# 1. Roll up Impl status from the legacy source map.
impl: dict[str, tuple[str, str]] = {}
result = subprocess.run(
    [sys.executable, str(SCRIPTS / "derive_module_impl.py")],
    check=True, capture_output=True, text=True,
)
for line in result.stdout.splitlines():
    if not line.strip():
        continue
    mod, status, note = line.split("\t", 2)
    impl[mod] = (status, note)

# 2. Hand off to parity_coverage.ledger with the seeded prior_impl.
sys.path.insert(0, str(SCRIPTS))
from parity_coverage import analyze, ledger        # noqa: E402

a = analyze()
text = ledger(a, prior_impl=impl)
OUT.write_text(text, encoding="utf-8")
print(f"wrote {OUT}")
print(f"modules: {len(a.modules)}  ported: {a.total_ported}  upstream it(): {a.total_it}")
print(f"impl seeded for: {len(impl)} modules")
missing_impl = sorted(set(a.modules) - set(impl))
print(f"impl unknown:    {len(missing_impl)} modules (will show `?`)")
